version: "3.8"

services:
  evently-app:
    image: cooey12/evently:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
